events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Корневая директория для статических файлов
        root /app/static;
        index index.html;

        # Проксирование запросов к FastAPI
        location / {
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Обработка статических файлов
        location /static/ {
            alias /app/static/;
        }

        # Обработка загруженных изображений
        location /images/ {
            alias /app/images/;
        }

        # Обработка шаблонов
        location /templates/ {
            alias /app/templates/;
        }

        # favicon
        location /favicon.ico {
            return 301 https://img.icons8.com/?size=100&id=ImvmbJAfHo6J&format=png&color=000000;
        }
    }
}